version: "3"

services:
  db:
    image: postgres:11.4-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=@BK19uYBT#
      - POSTGRES_DB=hotelbookingsystem
    ports:
      - 5434:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    command: bash -c "cd src && ./manage.py runserver 0.0.0.0:8000"
    ports:
      - 8010:8000
    env_file:
      - .env
