# Generated by Django 3.1.7 on 2021-09-05 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('room_no', models.CharField(max_length=100, unique=True, verbose_name='phone_no')),
                ('floor_no', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('bed_count', models.IntegerField()),
                ('price', models.FloatField()),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['room_no'], name='rooms_room_no_bcd67e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['floor_no'], name='rooms_floor_n_00af86_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['availability'], name='rooms_availab_76a49e_idx'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['bed_count'], name='rooms_bed_cou_adcbe7_idx'),
        ),
    ]
