# Generated by Django 3.1.7 on 2021-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='room',
            name='rooms_availab_76a49e_idx',
        ),
        migrations.RemoveIndex(
            model_name='room',
            name='rooms_bed_cou_adcbe7_idx',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='bed_count',
            new_name='capacity',
        ),
        migrations.RemoveField(
            model_name='room',
            name='availability',
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['capacity'], name='rooms_capacit_c8100e_idx'),
        ),
    ]
