# Generated by Django 3.1.7 on 2021-09-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('customer_phone_no', models.CharField(max_length=100, verbose_name='phone_no')),
                ('total_price', models.FloatField(default=0.0)),
                ('total_discount', models.FloatField(default=0.0)),
                ('reserve_time', models.DateTimeField(blank=True, null=True, verbose_name='last reservation time')),
                ('last_checkin_time', models.DateTimeField(blank=True, null=True, verbose_name='last checkin time')),
                ('last_checkout_time', models.DateTimeField(blank=True, null=True, verbose_name='last checkout time')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.room')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['customer_phone_no'], name='bookings_custome_a88b76_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['room'], name='bookings_room_id_4c7af2_idx'),
        ),
    ]
