# Generated by Django 3.1.7 on 2021-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_discount',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='reserve_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_end_time',
            field=models.DateTimeField(default='2021-09-06T05:20:29.636293+00:00', verbose_name='booking end time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_start_time',
            field=models.DateTimeField(default='2021-09-06T05:20:51.718624+00:00', verbose_name='booking start time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_time',
            field=models.DateTimeField(default='2021-09-06T05:21:02.901212+00:00', verbose_name='last reservation time'),
            preserve_default=False,
        ),
    ]
