# Generated by Django 3.1.7 on 2021-09-05 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=150)),
                ('updated_by', models.CharField(max_length=150)),
                ('phone_no', models.CharField(max_length=100, verbose_name='phone_no')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('others', 'others')], default='male', max_length=10)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('last_checkin', models.DateTimeField(verbose_name='last checkin')),
                ('last_checkout', models.DateTimeField(verbose_name='last checkout')),
                ('last_reservation', models.DateTimeField(verbose_name='last checkout')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'customers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone_no'], name='customers_phone_n_b5f83e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['first_name'], name='customers_first_n_887155_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='customers_email_92e882_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['country'], name='customers_country_5b383b_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['occupation'], name='customers_occupat_a591dc_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['gender'], name='customers_gender_6ae3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_checkin'], name='customers_last_ch_1a2475_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_checkout'], name='customers_last_ch_25cf19_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_reservation'], name='customers_last_re_774347_idx'),
        ),
    ]
