# Generated by Django 3.1.7 on 2021-09-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_last_ch_1a2475_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_last_ch_25cf19_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='customers_last_re_774347_idx',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_checkin',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_checkout',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_reservation',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_no',
            field=models.CharField(max_length=100, unique=True, verbose_name='phone_no'),
        ),
    ]
